### ISSUE TITLE
Code for ClinicalLongformer

### ISSUE THREAD

**Issue by jwaldor** [luoyuanlab/Clinical-Longformer#1]
Hi there,
I was not able to find the code relating to the paper "Clinical-Longformer and Clinical-BigBird: Transformers for long clinical sequences" in this repository. Do you know where I can find it? Thank you.
Best,
Jacob

**Comment by yikuan8** [comment]
Hi Jacob,

I am currently pressed on time. Once I have more bandwidth to clean the codes, we will release the codes for pre-training and fine-tuning . Here are some implementations that might be helpful.

i2b2 cleaning: https://github.com/EmilyAlsentzer/clinicalBERT/tree/master/downstream_tasks/i2b2_preprocessing
emrQA clearning: https://github.com/xiangyue9607/CliniRC/blob/master/src/preprocessing.py

**Comment by NtaylorOX** [comment]
Any update on this? Would be great to see the code :)

**Comment by yikuan8** [comment]
> Any update on this? Would be great to see the code :)

My bandwidth is currently limited. I will clean and upload the codes by the end of this month. Sorry about that!
