### ISSUE TITLE
request to opensource text processing code

### ISSUE THREAD

**Issue by whaleloops** [luoyuanlab/Clinical-Longformer#2]
Could you share some preprocessing code? especially related to 
![image](https://user-images.githubusercontent.com/31370581/170349611-13d8cc5a-a424-42cd-aca1-39529d730cb6.png)

Thanks in advance.

**Comment by yikuan8** [comment]
Please refer this [repo](https://github.com/kexinhuang12345/clinicalBERT/blob/master/preprocess.py).
