### ISSUE TITLE
Code for pre-training

### ISSUE THREAD

**Issue by NtaylorOX** [luoyuanlab/Clinical-Longformer#3]
Hi,

Do you have the code used for the actual LM pre-training?

Thanks

**Comment by yikuan8** [comment]
Here is an example
`CUDA_VISIBLE_DEVICES=1,2,3,4 python transformers/examples/pytorch/language-modeling/run_mlm.py --model_name_or_path google/bigbird-roberta-base --train_file mimic3_lm_train.txt --validation_file mimic3_lm_dev.txt --output_dir /home/ylo7832/cpbb/ --max_steps 300000 --per_device_train_batch_size 2 --per_device_eval_batch_size 2 --save_steps 30000 --eval_steps 30000 --max_seq_length 4096 --do_train --do_eval --fp16_backend amp --fp16 --learning_rate 3e-5 --warmup_steps 10000 --evaluation_strategy steps --resume_from_checkpoint /home/ylo7832/cpbb/checkpoint-180000/`

**Comment by NtaylorOX** [comment]
Thanks! Issue closed
