### ISSUE TITLE
issues about Clinical-BigBird

### ISSUE THREAD

**Issue by Ziyu-Jin** [luoyuanlab/Clinical-Longformer#4]
Hi，

I have a question. In the clinical-bigbird of huggingface, I found that there is no vocab.json in the file, but there is vocab.json in the clinical-longformer. I would like to ask if they share the same vocab, or where can I find the vocab.json file of clinical-bigbird?

Thanks！

**Comment by yikuan8** [comment]
No, it is slightly different from C-Longformer. See [here](https://github.com/huggingface/transformers/issues/1937) for how to get the vocab.
