### ISSUE TITLE
Clinical-Longformer   Attention_window

### ISSUE THREAD

**Issue by satya400** [luoyuanlab/Clinical-Longformer#5]
Thank you  @YIKUAN8  @luoyuanlab  for the Clinical-Longformer and weights.

Since Long Former has the attention_window  config parameter, can we use it for fine tuning the Clinical-Longformer also for the downstream tasks?

I am using the huggingface trainer for fine tuning and I tried to pass attention_window  to  TrainingArguments but I received an error.

Thanks
Satya

**Comment by yikuan8** [comment]
Hi Satya,

I used the default attention window when initiate Longformer. I can help more if you would like to share a snippet of your code. 

-Yikuan

**Comment by satya400** [comment]
Hi Yikuan,

Thanks for the quick response. I am tuning hyper parameters for a down stream task of classification. My input data is roughly 2000 char long. And I am using the hugging face trainer's  arguments as below.  I wanted to experiment with various attention window sizes ( like 128, 256 & 512) - but not able to pass this param to clinical long former.  Is it passible to change the attention param? Or should we pre-train the 'clinical long former' from scratch?
--------------------------------------------------------------------------------------
batch_size = 4  
logging_steps =  len(my_dataset["train"]) // batch_size
training_args = TrainingArguments(
                                  output_dir='....',
                                  num_train_epochs = 20, 
                                  learning_rate=2e-05,
                                  per_device_train_batch_size = batch_size,
                                  per_device_eval_batch_size = 2 * batch_size,
                                  weight_decay=0.01,
                                  evaluation_strategy  = "epoch",
                                  disable_tqdm=False,
                                  logging_steps=logging_steps,
                                  log_level="error",                                   
                                  #attention_window=256, #this is giving error
				)
-----------------------------------------------------------------------------------

**Comment by yikuan8** [comment]
That's true. _attention_window_ should be specified when you initialized a model not the trainer. If you would like to use customized _attention_window_, you have to train a language window from scratch. 

Given that your input data is roughly 2000 char long (probably 400 tokens?), I guess the default attention window size (=512 token) should be fine.

**Comment by satya400** [comment]
Thank you, Yikuan. I will continue with the default attention window for the time being and see how it goes.

**Comment by YunXi24** [comment]
I have  a debug when I run this model.
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [12, 1024, 1]], which is output 0 of ViewBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
If you have the same problem, can you answer it for me?
Thanks.

**Comment by satya400** [comment]
Hi @YIKUAN8

The current weights downloaded from your huggingface models are trained with max_position_embeddings  = 4096.  By any chance do you have a 2048 sequence length version (weights)?   For some small use cases, 4096 is an overkill.

Thanks
Satya

**Comment by yikuan8** [comment]
Satya,

Unfortunately I don't. I guess no significant performance decrease / extra training burdens will be observed if you use 4096 other than 2048. Please let me know if you decide to pre-train a 2048 LM and we can compare the difference there.
